config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :species, inclusion: { in: %w(dog cat turtle moose)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]


  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pets_path
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for(pet) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :species %>
        <%= f.input :found_on %>
        <%= f.submit %>
      <% end %>

    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<%= render "form", pet: @pet, greeting: "Hey there" %>

app/views/pets/index.html.erb
<div class="container pt-10vh">
  <div class="row">
    <% @pets.each do |pet| %>
      <div class="col-sm-4 col-md-6">
        <%= link_to pet_path(pet) do %>
          <div class="pet-card" style="background-image: url(<%= asset_path('dog') %>)">
            <p><%= pet.name %></p>
            <p><%= pet.address %></p>
            <p><%= pet.found_on %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= link_to new_pet_path do %>
    <div class="btn btn-primary">
      New Pet
    </div>
  <% end %>
</div>

app/views/pets/new.html.erb
<%= render "form", pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<p><%= @pet.address %></p>
<%= link_to "Edit pet", edit_pet_path(@pet) %>
<%= link_to pet_path(@pet), method: :delete, data: { confirm: "PLease me don't delete me, I just want a loving home" } do %>
  <i class="fas fa-trash"></i>
<% end %>


<% if @pet.found_on.present? %>
  <input type="checkbox" checked>
  <!-- <i class="fas fa-check-square"></i> -->
<% else %>
  <input type="checkbox">
  <!-- <i class="fas fa-check-square"></i> -->
<% end %>

<%= link_to "Home", pets_path  %>